### PR TITLE
Download otelcol builder binary

### LINKED ISSUE #20: Revert OTEL collector builder installation to binary download
[opentelemetry-collector-builder README instructions](https://github.com/observatorium/opentelemetry-collector-builder) are outdated and downloading the binary should be the right way to install it.

Related comment: https://github.com/jaegertracing/jaeger-otelcol/pull/18#issuecomment-757819212

### PR DESCRIPTION
**Pull request by albertteoh**
Signed-off-by: albertteoh <albert.teoh@logz.io>

Fixes #20 

Reverts the change made due to an outdated README instruction. The preferred way to install otel builder is to download the binary.

This PR also adds support for MacOS installations of otel builder.

### CODE REVIEW

**Comment by albertteoh** [comment]
This PR build fails with:
```
+ curl -sLo /home/runner/bin/opentelemetry-collector-builder https://github.com/observatorium/opentelemetry-collector-builder/releases/download/v0.2.0/opentelemetry-collector-builder_0.2.0_linux_amd64
+ chmod +x /home/runner/bin/opentelemetry-collector-builder
Makefile:26: recipe for target 'build-agent' failed
/home/runner/bin/opentelemetry-collector-builder: 1: /home/runner/bin/opentelemetry-collector-builder: Not: not found
```

It's because there is no such binary named `opentelemetry-collector-builder_0.2.0_linux_amd64`. The `amd64` suffix is derived from `go env GOARCH`. Replacing `amd64` with `x86_64` will work. 

A successful build of this PR depends on three things (I think, unless if we can somehow rename the released binary files in github):
- Merging https://github.com/observatorium/opentelemetry-collector-builder/pull/28.
- Create a new release with the corrected binary name: https://github.com/observatorium/opentelemetry-collector-builder/releases.
- Updating the `OTELCOL_BUILDER_VERSION` in this PR's Makefile to the latest release version of otel builder.

**Comment by jpkrohling** [comment]
There's a new version of the OpenTelemetry Collector available, so, I should be releasing a new version of the builder soon.

**Comment by albertteoh** [comment]
@kevinearls @jpkrohling I've upgraded the version in the Makefile to pickup the MacOS compatible binary release version 0.4.1 and also refactored the `otelcol-builder` make target to move it to a shell script to keep the Makefile clean and easier to implement more sophisticated installation logic for the otelcol-builder, such as version checks.

**Review by kevinearls — APPROVED** [review]
LGTM

**Pull request merged**
